version: '3'

services:
  web:
    build:
      context: com.jpagliuca.recipi/
      dockerfile: provision/dockerfile-web
    container_name: recipi_web
    command: npm start
    # command: ls -a
    ports:
      - "8080:8080"
    volumes:
      - ./com.jpagliuca.recipi/src/main/web:/app
    networks: 
      - apps
    # depends_on:
    #   - api
  # api:
  proxy:
    image: nginx:1.13.1
    container_name: recipi_proxy
    ports:
      - "8123:8123"
    volumes:
      - ./com.jpagliuca.recipi/provision/recipi-proxy.conf:/etc/nginx/conf.d/default.conf
    networks: 
      - apps
      - proxy

networks:
  apps:
    internal: true
  proxy:
    internal: false
