# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-12 06:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recipi', '0003_recipe'),
    ]

    operations = [
        migrations.CreateModel(
            name='Step',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField()),
                ('unit', models.CharField(max_length=16)),
                ('amount', models.IntegerField()),
            ],
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='name',
            field=models.CharField(max_length=32),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='description',
            field=models.CharField(max_length=256),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='difficulty',
            field=models.CharField(choices=[('F', 'Foetus'), ('E', 'Breezy'), ('M', 'Tricky'), ('H', 'Expert')], max_length=8),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='image',
            field=models.CharField(max_length=32),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='name',
            field=models.CharField(max_length=32),
        ),
        migrations.AlterField(
            model_name='tag',
            name='name',
            field=models.CharField(max_length=32),
        ),
        migrations.AddField(
            model_name='step',
            name='ingredient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recipi.Ingredient'),
        ),
        migrations.AddField(
            model_name='step',
            name='recipe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recipi.Recipe'),
        ),
        migrations.AlterUniqueTogether(
            name='step',
            unique_together=set([('number', 'recipe')]),
        ),
    ]
