# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-14 00:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recipi', '0005_step_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='Time',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prep', models.IntegerField(default=0)),
                ('cook', models.IntegerField(default=0)),
                ('other', models.IntegerField(default=0)),
            ],
        ),
        migrations.RemoveField(
            model_name='recipe',
            name='time_cook',
        ),
        migrations.RemoveField(
            model_name='recipe',
            name='time_other',
        ),
        migrations.RemoveField(
            model_name='recipe',
            name='time_prep',
        ),
        migrations.AlterField(
            model_name='step',
            name='recipe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='recipi.Recipe'),
        ),
        migrations.AddField(
            model_name='recipe',
            name='time',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='recipi.Time'),
        ),
    ]
