# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-03-27 10:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipi', '0007_auto_20170325_2303'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='difficulty',
            field=models.CharField(choices=[('E', 'Breezy'), ('M', 'Tricky'), ('H', 'Expert')], max_length=8),
        ),
    ]
