# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-03-27 11:04
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipi', '0008_auto_20170327_1021'),
    ]

    operations = [
        migrations.RenameField(
            model_name='step',
            old_name='ingredient',
            new_name='ingredient_pk',
        ),
    ]
