# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-04-27 00:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipi', '0009_auto_20170327_1104'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='image',
            field=models.ImageField(upload_to=b''),
        ),
    ]
