# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-04-27 08:26
from __future__ import unicode_literals

from django.db import migrations, models
import recipiApi.recipi.models


class Migration(migrations.Migration):

    dependencies = [
        ('recipi', '0010_auto_20170427_0034'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='image',
            field=models.ImageField(upload_to=recipiApi.recipi.models.randomize_filename),
        ),
    ]
